// Builds the vendored Material assets (run from app/vendor-build):
//   ../static/vendor/material.js  - @material/web bundle
//   ../static/vendor/theme.css    - M3 color tokens (light+dark) from the seed + fonts
//   ../static/vendor/fonts/       - Roboto + Material Symbols
// Run: node scripts/build-theme.mjs
import { build } from 'esbuild';
import { mkdirSync, copyFileSync, writeFileSync, rmSync } from 'fs';

const SEED = '#1a73e8';
const OUT = '../static/vendor';
mkdirSync(`${OUT}/fonts`, { recursive: true });

await build({
  entryPoints: ['scripts/material-entry.js'],
  bundle: true, minify: true, format: 'esm',
  outfile: `${OUT}/material.js`,
});

// material-color-utilities ships extensionless ESM imports Node can't load directly —
// bundle it first, then import the bundle.
await build({ entryPoints: ['scripts/gen-tokens.js'], bundle: true, format: 'esm', outfile: '.tokens-bundle.mjs' });
const { generate } = await import(new URL('../.tokens-bundle.mjs', import.meta.url));
const scheme = generate(SEED);
rmSync('.tokens-bundle.mjs');

for (const f of ['roboto-latin-400-normal.woff2', 'roboto-latin-500-normal.woff2', 'roboto-latin-700-normal.woff2'])
  copyFileSync(`node_modules/@fontsource/roboto/files/${f}`, `${OUT}/fonts/${f}`);
copyFileSync('node_modules/material-symbols/material-symbols-outlined.woff2', `${OUT}/fonts/material-symbols-outlined.woff2`);

writeFileSync(`${OUT}/theme.css`, `/* Generated by app/vendor-build/scripts/build-theme.mjs — do not edit. Seed: ${SEED} */
@font-face { font-family: Roboto; font-weight: 400; src: url(/static/vendor/fonts/roboto-latin-400-normal.woff2) format('woff2'); }
@font-face { font-family: Roboto; font-weight: 500; src: url(/static/vendor/fonts/roboto-latin-500-normal.woff2) format('woff2'); }
@font-face { font-family: Roboto; font-weight: 700; src: url(/static/vendor/fonts/roboto-latin-700-normal.woff2) format('woff2'); }
@font-face { font-family: 'Material Symbols Outlined'; font-style: normal; font-weight: 100 700;
  src: url(/static/vendor/fonts/material-symbols-outlined.woff2) format('woff2'); }
md-icon, .msym { font-family: 'Material Symbols Outlined'; font-weight: normal; font-style: normal;
  font-size: 24px; line-height: 1; letter-spacing: normal; text-transform: none; display: inline-block;
  white-space: nowrap; word-wrap: normal; direction: ltr; -webkit-font-smoothing: antialiased; }

:root, :root[data-theme="light"] {
${scheme.light}
  color-scheme: light;
}
@media (prefers-color-scheme: dark) { :root:not([data-theme="light"]) {
${scheme.dark}
  color-scheme: dark;
} }
:root[data-theme="dark"] {
${scheme.dark}
  color-scheme: dark;
}
`);
console.log('vendor assets built');
